### ISSUE TITLE
843: error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by airob0t** [samyk/keysweeper#2]
843: error: void value not ignored as it ought to be
uint8_t got = radio.read(&p, PKT_SIZE);

arduino ide 1.0.6

**Comment by samyk** [comment]
Are you using maniacbuf's RF24 library or a different version/fork? (There are a ton of forks but you should make sure you're using maniacbug's: https://github.com/maniacbug/RF24)

**Comment by airob0t** [comment]
solved,thank you.
