### ISSUE TITLE
W25Q80BV flash Schematic

### ISSUE THREAD

**Issue by yo0x** [samyk/keysweeper#7]
It would be possible to add a Schematic with the W25Q80BV flash connection?

**Comment by samyk** [comment]
Here's the pinout if someone wants to produce it:
 1: CS: 10
 2: DO: 12
 3: WP: not used
 4: GND: GND
 5: DI: 11
 6: CLK: 13
 7: HOLD: not used
 8: VCC: 3.3 VCC
