### ISSUE TITLE
RF24 Library

### ISSUE THREAD

**Issue by ikarus23** [samyk/keysweeper#8]
I wonder what nRF24 library should I use to satisfy the `RF24.h` and the `nRF24L01.h` import?
I used the one from [TMRh20/RF24](https://github.com/TMRh20/RF24) repo. But the `radio.read()` is a void function and therefore [lines like this](https://github.com/samyk/keysweeper/blob/master/keysweeper_mcu_src/keysweeper_mcu_src.ino#L916) do not work...

**Comment by ikarus23** [comment]
Oh, sorry for not looking at the closed issues first...
I just noticed issue https://github.com/samyk/keysweeper/issues/6... Wouldn't it be the easiest way to ship them with our repo?

**Comment by samyk** [comment]
Using maniacbug's RF24 library as it's the most ubiquitous version. I could ship it with KeySweeper but it would be redundant -- the forks should actually have different names and I have thought about producing a fork with a different name and functions that would simplify KeySweeper, but hasn't been a priority.

**Comment by ikarus23** [comment]
Ok, so updating the [the software section](https://github.com/samyk/keysweeper#u-software) of the readme would be great.

FYI: I searched something like "nrf24 lib arduino" and got right at [this arduino page](http://playground.arduino.cc/InterfacingWithHardware/Nrf24L01). There are a lot of RF24 libs there, but none of them refers to maniacbug's lib... :/

**Comment by samyk** [comment]
I welcome contributions/git pulls

**Comment by ikarus23** [comment]
Hehe, who doesn't?
Here you go: https://github.com/samyk/keysweeper/pull/9

**Comment by samyk** [comment]
Thanks!
